[2021-12-13 09:30:12,876] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-12T09:29:57.928788+00:00 [queued]>
[2021-12-13 09:30:12,907] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-12T09:29:57.928788+00:00 [queued]>
[2021-12-13 09:30:12,908] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 09:30:12,909] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-13 09:30:12,909] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 09:30:12,923] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-12-12T09:29:57.928788+00:00
[2021-12-13 09:30:12,928] {standard_task_runner.py:52} INFO - Started process 106 to run task
[2021-12-13 09:30:12,933] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'cleansing_dag', 'writeOut', '2021-12-12T09:29:57.928788+00:00', '--job-id', '62', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpo317dwaw', '--error-file', '/tmp/tmpmaxowfcf']
[2021-12-13 09:30:12,936] {standard_task_runner.py:77} INFO - Job 62: Subtask writeOut
[2021-12-13 09:30:12,983] {logging_mixin.py:104} INFO - Running <TaskInstance: cleansing_dag.writeOut 2021-12-12T09:29:57.928788+00:00 [running]> on host 8ea24132e477
[2021-12-13 09:30:13,029] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-12-12T09:29:57.928788+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-12T09:29:57.928788+00:00
[2021-12-13 09:30:19,394] {python.py:118} INFO - Done. Returned value was: None
[2021-12-13 09:30:19,977] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=writeOut, execution_date=20211212T092957, start_date=20211213T093012, end_date=20211213T093019
[2021-12-13 09:30:20,068] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-13 09:30:20,146] {local_task_job.py:146} INFO - Task exited with return code 0
