[2021-12-29 15:01:56,296] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.cleanse_kym 2021-12-28T15:01:54.913843+00:00 [queued]>
[2021-12-29 15:01:56,317] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.cleanse_kym 2021-12-28T15:01:54.913843+00:00 [queued]>
[2021-12-29 15:01:56,318] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 15:01:56,318] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-29 15:01:56,319] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-29 15:01:56,331] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): cleanse_kym> on 2021-12-28T15:01:54.913843+00:00
[2021-12-29 15:01:56,337] {standard_task_runner.py:52} INFO - Started process 22235 to run task
[2021-12-29 15:01:56,340] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'cleanse_kym', '2021-12-28T15:01:54.913843+00:00', '--job-id', '512', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpfpbw1nzx', '--error-file', '/tmp/tmptfv6oin4']
[2021-12-29 15:01:56,341] {standard_task_runner.py:77} INFO - Job 512: Subtask cleanse_kym
[2021-12-29 15:01:56,391] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.cleanse_kym 2021-12-28T15:01:54.913843+00:00 [running]> on host 34521d0e1651
[2021-12-29 15:01:56,459] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=cleanse_kym
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T15:01:54.913843+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-28T15:01:54.913843+00:00
[2021-12-29 15:04:41,318] {python.py:151} INFO - Done. Returned value was: None
[2021-12-29 15:04:41,373] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=cleanse_kym, execution_date=20211228T150154, start_date=20211229T150156, end_date=20211229T150441
[2021-12-29 15:04:41,415] {local_task_job.py:151} INFO - Task exited with return code 0
