[2021-12-09 16:05:02,448] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-08T16:04:42.997356+00:00 [queued]>
[2021-12-09 16:05:02,470] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-08T16:04:42.997356+00:00 [queued]>
[2021-12-09 16:05:02,471] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 16:05:02,471] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-09 16:05:02,472] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-09 16:05:02,485] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-12-08T16:04:42.997356+00:00
[2021-12-09 16:05:02,490] {standard_task_runner.py:52} INFO - Started process 287 to run task
[2021-12-09 16:05:02,493] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'cleansing_dag', 'writeOut', '2021-12-08T16:04:42.997356+00:00', '--job-id', '55', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpjyi7vckd', '--error-file', '/tmp/tmpekdyk10q']
[2021-12-09 16:05:02,495] {standard_task_runner.py:77} INFO - Job 55: Subtask writeOut
[2021-12-09 16:05:02,533] {logging_mixin.py:104} INFO - Running <TaskInstance: cleansing_dag.writeOut 2021-12-08T16:04:42.997356+00:00 [running]> on host 8ea24132e477
[2021-12-09 16:05:02,570] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-12-08T16:04:42.997356+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-08T16:04:42.997356+00:00
[2021-12-09 16:05:09,373] {python.py:118} INFO - Done. Returned value was: None
[2021-12-09 16:05:09,747] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=writeOut, execution_date=20211208T160442, start_date=20211209T160502, end_date=20211209T160509
[2021-12-09 16:05:09,774] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-09 16:05:09,857] {local_task_job.py:146} INFO - Task exited with return code 0
