[2021-12-13 14:36:23,097] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-12T14:36:21.692424+00:00 [queued]>
[2021-12-13 14:36:23,118] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: cleansing_dag.writeOut 2021-12-12T14:36:21.692424+00:00 [queued]>
[2021-12-13 14:36:23,119] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 14:36:23,119] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-13 14:36:23,120] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-13 14:36:23,138] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-12-12T14:36:21.692424+00:00
[2021-12-13 14:36:23,142] {standard_task_runner.py:52} INFO - Started process 1254 to run task
[2021-12-13 14:36:23,145] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'cleansing_dag', 'writeOut', '2021-12-12T14:36:21.692424+00:00', '--job-id', '15', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmpy6kh3bip', '--error-file', '/tmp/tmpbiwu_a9f']
[2021-12-13 14:36:23,146] {standard_task_runner.py:77} INFO - Job 15: Subtask writeOut
[2021-12-13 14:36:23,184] {logging_mixin.py:104} INFO - Running <TaskInstance: cleansing_dag.writeOut 2021-12-12T14:36:21.692424+00:00 [running]> on host c2664a5050de
[2021-12-13 14:36:23,231] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-12-12T14:36:21.692424+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-12-12T14:36:21.692424+00:00
[2021-12-13 14:36:24,280] {python.py:118} INFO - Done. Returned value was: None
[2021-12-13 14:36:24,294] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=writeOut, execution_date=20211212T143621, start_date=20211213T143623, end_date=20211213T143624
[2021-12-13 14:36:24,327] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-13 14:36:24,373] {local_task_job.py:146} INFO - Task exited with return code 0
