[2021-12-28 18:01:59,623] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.cleanse_vision 2021-12-28T18:01:57.682762+00:00 [queued]>
[2021-12-28 18:01:59,640] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: cleansing_dag.cleanse_vision 2021-12-28T18:01:57.682762+00:00 [queued]>
[2021-12-28 18:01:59,641] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 18:01:59,642] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-28 18:01:59,642] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-28 18:01:59,653] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): cleanse_vision> on 2021-12-28T18:01:57.682762+00:00
[2021-12-28 18:01:59,657] {standard_task_runner.py:52} INFO - Started process 62 to run task
[2021-12-28 18:01:59,661] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'cleansing_dag', 'cleanse_vision', '2021-12-28T18:01:57.682762+00:00', '--job-id', '146', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/kym_cleansing.py', '--cfg-path', '/tmp/tmppgoktlj4', '--error-file', '/tmp/tmpzj4c0zz0']
[2021-12-28 18:01:59,663] {standard_task_runner.py:77} INFO - Job 146: Subtask cleanse_vision
[2021-12-28 18:01:59,705] {logging_mixin.py:109} INFO - Running <TaskInstance: cleansing_dag.cleanse_vision 2021-12-28T18:01:57.682762+00:00 [running]> on host e75bb9f39fa6
[2021-12-28 18:01:59,767] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=cleansing_dag
AIRFLOW_CTX_TASK_ID=cleanse_vision
AIRFLOW_CTX_EXECUTION_DATE=2021-12-28T18:01:57.682762+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-28T18:01:57.682762+00:00
[2021-12-28 18:03:46,048] {python.py:151} INFO - Done. Returned value was: None
[2021-12-28 18:03:46,069] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=cleansing_dag, task_id=cleanse_vision, execution_date=20211228T180157, start_date=20211228T180159, end_date=20211228T180346
[2021-12-28 18:03:46,097] {local_task_job.py:208} WARNING - State of this instance has been externally set to success. Terminating instance.
