[2021-12-08 18:50:47,317] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.writeOut 2021-11-21T18:11:09.696138+00:00 [queued]>
[2021-12-08 18:50:47,347] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.writeOut 2021-11-21T18:11:09.696138+00:00 [queued]>
[2021-12-08 18:50:47,348] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 18:50:47,348] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-12-08 18:50:47,348] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-12-08 18:50:47,361] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-11-21T18:11:09.696138+00:00
[2021-12-08 18:50:47,366] {standard_task_runner.py:52} INFO - Started process 117 to run task
[2021-12-08 18:50:47,369] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'writeOut', '2021-11-21T18:11:09.696138+00:00', '--job-id', '40', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpmg7k4chw', '--error-file', '/tmp/tmp9o25dzk8']
[2021-12-08 18:50:47,370] {standard_task_runner.py:77} INFO - Job 40: Subtask writeOut
[2021-12-08 18:50:47,423] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.writeOut 2021-11-21T18:11:09.696138+00:00 [running]> on host 8c41fc747080
[2021-12-08 18:50:47,573] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-11-21T18:11:09.696138+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-11-21T18:11:09.696138+00:00
[2021-12-08 18:50:56,102] {python.py:118} INFO - Done. Returned value was: None
[2021-12-08 18:50:56,963] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=writeOut, execution_date=20211121T181109, start_date=20211208T185047, end_date=20211208T185056
[2021-12-08 18:50:57,058] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-12-08 18:50:57,148] {local_task_job.py:146} INFO - Task exited with return code 0
