[2021-12-31 15:52:42,855] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main_dag.create_origin_dimension_query 2021-12-31T15:47:34.975008+00:00 [queued]>
[2021-12-31 15:52:42,874] {taskinstance.py:903} INFO - Dependencies all met for <TaskInstance: main_dag.create_origin_dimension_query 2021-12-31T15:47:34.975008+00:00 [queued]>
[2021-12-31 15:52:42,875] {taskinstance.py:1094} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 15:52:42,875] {taskinstance.py:1095} INFO - Starting attempt 1 of 2
[2021-12-31 15:52:42,876] {taskinstance.py:1096} INFO - 
--------------------------------------------------------------------------------
[2021-12-31 15:52:42,897] {taskinstance.py:1114} INFO - Executing <Task(PythonOperator): create_origin_dimension_query> on 2021-12-31T15:47:34.975008+00:00
[2021-12-31 15:52:42,904] {standard_task_runner.py:52} INFO - Started process 17050 to run task
[2021-12-31 15:52:42,908] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'main_dag', 'create_origin_dimension_query', '2021-12-31T15:47:34.975008+00:00', '--job-id', '149', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/main_dag.py', '--cfg-path', '/tmp/tmp3haiyh1j', '--error-file', '/tmp/tmp6wu8dhum']
[2021-12-31 15:52:42,910] {standard_task_runner.py:77} INFO - Job 149: Subtask create_origin_dimension_query
[2021-12-31 15:52:42,961] {logging_mixin.py:109} INFO - Running <TaskInstance: main_dag.create_origin_dimension_query 2021-12-31T15:47:34.975008+00:00 [running]> on host 8e99a5d40b8f
[2021-12-31 15:52:43,038] {taskinstance.py:1251} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=main_dag
AIRFLOW_CTX_TASK_ID=create_origin_dimension_query
AIRFLOW_CTX_EXECUTION_DATE=2021-12-31T15:47:34.975008+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-12-31T15:47:34.975008+00:00
[2021-12-31 15:52:43,169] {python.py:151} INFO - Done. Returned value was: None
[2021-12-31 15:52:43,186] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=main_dag, task_id=create_origin_dimension_query, execution_date=20211231T154734, start_date=20211231T155242, end_date=20211231T155243
[2021-12-31 15:52:43,242] {local_task_job.py:151} INFO - Task exited with return code 0
