[2021-11-21 18:31:29,822] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.writeOut 2021-11-21T18:30:09.629274+00:00 [queued]>
[2021-11-21 18:31:29,849] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: first_dag.writeOut 2021-11-21T18:30:09.629274+00:00 [queued]>
[2021-11-21 18:31:29,850] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 18:31:29,850] {taskinstance.py:1043} INFO - Starting attempt 1 of 2
[2021-11-21 18:31:29,850] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-11-21 18:31:29,862] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): writeOut> on 2021-11-21T18:30:09.629274+00:00
[2021-11-21 18:31:29,866] {standard_task_runner.py:52} INFO - Started process 122 to run task
[2021-11-21 18:31:29,868] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'first_dag', 'writeOut', '2021-11-21T18:30:09.629274+00:00', '--job-id', '35', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/first_dag.py', '--cfg-path', '/tmp/tmpsxtuu51s', '--error-file', '/tmp/tmpd2qrq2ie']
[2021-11-21 18:31:29,870] {standard_task_runner.py:77} INFO - Job 35: Subtask writeOut
[2021-11-21 18:31:29,920] {logging_mixin.py:104} INFO - Running <TaskInstance: first_dag.writeOut 2021-11-21T18:30:09.629274+00:00 [running]> on host 5212096de831
[2021-11-21 18:31:29,960] {taskinstance.py:1257} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=first_dag
AIRFLOW_CTX_TASK_ID=writeOut
AIRFLOW_CTX_EXECUTION_DATE=2021-11-21T18:30:09.629274+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-11-21T18:30:09.629274+00:00
[2021-11-21 18:31:36,402] {python.py:118} INFO - Done. Returned value was: None
[2021-11-21 18:31:36,415] {taskinstance.py:1166} INFO - Marking task as SUCCESS. dag_id=first_dag, task_id=writeOut, execution_date=20211121T183009, start_date=20211121T183129, end_date=20211121T183136
[2021-11-21 18:31:36,441] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-11-21 18:31:36,510] {local_task_job.py:146} INFO - Task exited with return code 0
